// Code generated by mockery. DO NOT EDIT.

package services

import mock "github.com/stretchr/testify/mock"

// MockIPasswordService is an autogenerated mock type for the IPasswordService type
type MockIPasswordService struct {
	mock.Mock
}

type MockIPasswordService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIPasswordService) EXPECT() *MockIPasswordService_Expecter {
	return &MockIPasswordService_Expecter{mock: &_m.Mock}
}

// Hash provides a mock function with given fields: password
func (_m *MockIPasswordService) Hash(password string) (string, error) {
	ret := _m.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(password)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIPasswordService_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type MockIPasswordService_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
//   - password string
func (_e *MockIPasswordService_Expecter) Hash(password interface{}) *MockIPasswordService_Hash_Call {
	return &MockIPasswordService_Hash_Call{Call: _e.mock.On("Hash", password)}
}

func (_c *MockIPasswordService_Hash_Call) Run(run func(password string)) *MockIPasswordService_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIPasswordService_Hash_Call) Return(_a0 string, _a1 error) *MockIPasswordService_Hash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIPasswordService_Hash_Call) RunAndReturn(run func(string) (string, error)) *MockIPasswordService_Hash_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function with given fields: hashed, plain
func (_m *MockIPasswordService) Verify(hashed string, plain string) error {
	ret := _m.Called(hashed, plain)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(hashed, plain)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIPasswordService_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockIPasswordService_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - hashed string
//   - plain string
func (_e *MockIPasswordService_Expecter) Verify(hashed interface{}, plain interface{}) *MockIPasswordService_Verify_Call {
	return &MockIPasswordService_Verify_Call{Call: _e.mock.On("Verify", hashed, plain)}
}

func (_c *MockIPasswordService_Verify_Call) Run(run func(hashed string, plain string)) *MockIPasswordService_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockIPasswordService_Verify_Call) Return(_a0 error) *MockIPasswordService_Verify_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIPasswordService_Verify_Call) RunAndReturn(run func(string, string) error) *MockIPasswordService_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIPasswordService creates a new instance of MockIPasswordService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIPasswordService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIPasswordService {
	mock := &MockIPasswordService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
